# Generated by Django 3.1.4 on 2020-12-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('assignedTo', models.CharField(max_length=10)),
                ('priority', models.IntegerField(max_length=1)),
            ],
        ),
    ]
