# Generated by Django 3.1.4 on 2020-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
